version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
  - package-ecosystem: 'npm'
    directory: '/apps/docs'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(docs)'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
  - package-ecosystem: 'npm'
    directory: '/apps/cli'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(cli)'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
  - package-ecosystem: 'npm'
    directory: '/packages/composables'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(composables)'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
  - package-ecosystem: 'npm'
    directory: '/packages/config'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(config)'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
  - package-ecosystem: 'npm'
    directory: '/packages/metadata'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(metadata)'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
  - package-ecosystem: 'npm'
    directory: '/packages/nuxt'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(nuxt)'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
  - package-ecosystem: 'npm'
    directory: '/packages/plugins'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(plugins)'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
  - package-ecosystem: 'npm'
    directory: '/packages/utils'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(utils)'
    groups:
      development:
        dependency-type: 'development'
      production:
        dependency-type: 'production'
