packages:
  - packages/*
  - apps/*
  - packages/nuxt/playground
  - '!packages/nuxt/test'
catalog:
  '@floating-ui/vue': ^1.1.6
  '@maas/magic-timer': ^1.0.1
  '@maas/mirror': ^0.11.0
  '@maas/vue-primitive': ^1.1.0
  '@maas/wheel-gestures': ^1.0.0
  '@nuxt/kit': ^3.15.2
  '@nuxt/schema': ^3.15.2
  '@nuxtjs/tailwindcss': ^6.13.1
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.10.7
  '@vueuse/core': '>=12.4.0'
  '@vueuse/integrations': '>=12.4.0'
  defu: ^6.1.4
  esno: ^4.8.0
  focus-trap: ^7.6.4
  fs-extra: ^11.3.0
  hls.js: ^1.5.19
  luxon: ^3.5.0
  mitt: ^3.0.1
  motion: ^10.18.0
  nuxt: ^3.15.2
  tailwindcss: ^3.4.17
  tsup: ^8.3.5
  typescript: 5.6.3
  universal-cookie: ^7.2.2
  vue: ^3.5.13
